
from snakemake.utils import min_version
min_version("7.0")

configfile: "config/config.yaml"

# define which output files you would like to generate
rule all:
    input:
        'data/sample1.h5ad'


module download_data:
    snakefile: "rules/download_data.smk"
    config: config

use rule * from download_data as dwn_*

